### ISSUE TITLE
Work with leiningen 2

### ISSUE THREAD

**Issue by deflexor** [hozumi/hiccup-bridge#4]
Hello, just installed as leinengen 2 plugin via file:
~/.lein/profiles.clj

And getting this error:

$ lein hicv 2clj 1.html 
Could not locate to_hiccup/core__init.class or to_hiccup/core.clj on classpath:

**Comment by hozumi** [comment]
hmm, the problem doesn't occur in my environment.

```
% lein version
Leiningen 2.0.0-preview10 on Java 1.6.0_31 Java HotSpot(TM) 64-Bit Server VM
```

```
% cat ~/.lein/profiles.clj
{:user {:plugins [[lein-swank "1.4.4"]
                  [lein-clojars "0.9.0"]
                  [lein-midje "2.0.0-SNAPSHOT"]
                  [org.clojars.hozumi/hiccup-bridge "1.0.0-SNAPSHOT"]
                  [lein-cljsbuild "0.2.5"]]}}
```

```
% curl https://github.com/ > 1.html
% lein hicv 2clj 1.html
% ls -l hicv/
total 48
-rw-r--r--  1 fatrow  staff  22009 10  6 03:46 1.clj
```

Could you show me `profiles.clj` and `lein version`?

**Comment by hozumi** [comment]
Sorry, I referred old repository.
The problem occurred in my environment.

**Comment by deflexor** [comment]
Hello, thank you for fast reply, here is mine profiles.clj

`{:user {:plugins  [[hiccup-bridge "1.0.0-SNAPSHOT"]  ]}}`

So i changed it to match yours and it seem working now, thanks!
This way it works:

`{:user {:plugins  [[org.clojars.hozumi/hiccup-bridge "1.0.0-SNAPSHOT"]  ]}}`

**Comment by hozumi** [comment]
Fixed. Please use new repository `[hiccup-bridge "1.0.0-SNAPSHOT"]`
Thank you for the report!
