### ISSUE TITLE
What is the lein and command line syntax

### ISSUE THREAD

**Issue by GHExplorer** [hozumi/hiccup-bridge#7]
Hi Takahiro,

Sorry, I don't know how this works.

I tried running it with an index.html file, in the hiccup-bridge project folder, 

```
 lein hicv 2clj index.html
```

and I just get an 'hicv is not a task' error.

In my profiles.clj, in the :plugins section, there is a [org.clojars.hozumi/hiccup-bridge "1.0.1"]

I tried generating a standalone version of Hiccup-bridge, going to the project/target folder, and then

```
 java -jar hiccup-bridge-1.0.1-standalone.jar hicv 2clj index.html
```

, and get a file not found error.

I then tried

```
 java -jar hiccup-bridge-1.0.1-standalone.jar index.html
```

, and it doesn't understand the <!doctype> tag.

If I remove the tag, then it's unable to resolve the <html> symbol.

Clueless, here.  How should this be run, standalone?

**Comment by hozumi** [comment]
Hi GHExplorer,

The dependency should be `[hiccup-bridge "1.0.1"]` .
So `~/.lein/profiles.clj` should be something like this:

```
{:user {:plugins [[hiccup-bridge "1.0.1"]]}}
```

I've confirmed that  hiccup-bridge 1.0.1 worked well on Leiningen 2.5.3.

**Comment by GHExplorer** [comment]
Thanks Hozumi,

But the results are all the same as before.  It must be a problem with the syntax.

My user profile in profiles.clj is

{:user
  {
  :java-cmd "C:\Java\bin\java.exe"
  :plugins [ [lein-localrepo "0.5.3"]
  [lein-try "0.4.3"]
  [hiccup-bridge "1.0.1"]
    ]
   }
 }

After putting the index.html file inside the hicv folder within the project folder, this command

```
lein hicv 2clj
```

returns the error

```
'hicv' is not a task. See 'lein help'.
```

This command

```
java -jar hiccup-bridge-1.0.1-standalone.jar index.html
```

returns an error

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: <!doctype in this context, compiling:(.....\hiccup-bridge\target\index.html:0:0)
```

This command

```
(hicv/html->hiccup "<foo><bar>buzz</bar></foo>")
```

works fine, inside the repl.

But this command inside the repl

```
( html-file->hiccup-file index.html )
```

returns an error

```
hiccup-bridge.core=> CompilerException java.lang.ClassNotFoundException: index.html, compiling: (...\AppData\Local\Temp\form-init2796367145974866822.clj:1:1) 
```

**Comment by hozumi** [comment]
I tested with your profiles.clj on OS X, and it works fine.
I think the problem may be related to Windows, because I didn't test on Windows.
I will test on Windows tonight, so please wait a little while.

**Comment by hozumi** [comment]
I've tested hiccup-bridge 1.0.1 on Windows 7, Leiningen 2.5.3 and Java 1.8.0_31 and it works fine.
Could you tell me the versions of your environment?

And when I tried to use your profiles.clj as it is, following error occurred:

```
C:\Users\fatrow\code\hicvtest>lein version
Error reading profiles.clj from C:\Users\fatrow\.lein
java.lang.RuntimeException: Unsupported escape character: \J
 at clojure.lang.Util.runtimeException (Util.java:221)
    clojure.lang.LispReader$StringReader.invoke (LispReader.java:569)
    clojure.lang.LispReader.read (LispReader.java:263)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1200)
    clojure.lang.LispReader$MapReader.invoke (LispReader.java:1158)
    clojure.lang.LispReader.read (LispReader.java:263)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1200)
```

The :java-cmd path you specified in profiles.clj is not a valid String.
This error can be solved by changing `"C:\Java\bin\java.exe"` to `"C:\\Java\\bin\\java.exe"` or `"C:/Java/bin/java.exe"`.

**Comment by hozumi** [comment]
```
java -jar hiccup-bridge-1.0.1-standalone.jar index.html
```

hiccup-bridge doesn't include a -main function in the namespace and :main key in project.clj.
These are required when jar is specified as [an executable jar](https://en.wikipedia.org/wiki/JAR_%28file_format%29#Executable_JAR_files).
See
http://clojure.org/repl_and_main
https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#uberjar

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: <!doctype in this context, compiling:(.....\hiccup-bridge\target\index.html:0:0)
```

The above message means the index.html file was being interpreted as a code.

``` clojure
( html-file->hiccup-file index.html )
```

html-file->hiccup-file requires a string as file path, so `index.html` should be `"index.html"`:

``` clojure
( html-file->hiccup-file "index.html")
```

**Comment by GHExplorer** [comment]
Thanks Hozumi,

Ugh.  I can't believe, I didn't check whether a main function was defined.  Ok, understood about the standalone.

I tried (... hiccup-file "index.html" ) command, and it worked fine.  Thanks.

Regarding the java path, my profiles.clj actually does have the escape characters.  It shows up as double slashes, after pasting from the text editor, and before posting the comment.

{:user
  {
  :java-cmd "C:\Java\bin\java.exe"
  :plugins [ [lein-localrepo "0.5.3"]
  [lein-try "0.4.3"]
  [hiccup-bridge "1.0.1"]
    ]
   }
 }

Before I click "Comment", the pasted projects.clj content above, has the double slashes.  Let's see what happens, after this is posted...

Confirmed.  When the contents of projects.clj are pasted from UltraEdit, it shows up correctly as double slashes.  But as soon as the comment is posted, it's stored (correctly, in a sense) as single slashes.

Try it.  Paste a path with double slashes, into a comment area, then post.  See what happens.

**Comment by hozumi** [comment]
```
'hicv' is not a task. See 'lein help'.
```

If `lein hicv` is still not recognized,  try `lein help` to see `hicv` and other plugins are listed.
Do the other plugins such as `lein-localrepo` and `lein-try` work?
Where is `profiles.clj` file?

**Comment by hozumi** [comment]
> Regarding the java path, my profiles.clj actually does have the escape characters.

I understand.

**Comment by GHExplorer** [comment]
The hicv plugin - it happens only on a Windows 8.1 pc, so far.  This obviously isn't a hiccup issue, I'll figure it out. 

Thanks, hozumi.
